/*
 * This file is generated by jOOQ.
 */
package br.com.kleston.projects.delivery.model.jooq;


import br.com.kleston.projects.delivery.model.jooq.tables.Accounts;
import br.com.kleston.projects.delivery.model.jooq.tables.Orders;
import br.com.kleston.projects.delivery.model.jooq.tables.OrdersFoods;
import br.com.kleston.projects.delivery.model.jooq.tables.Products;
import br.com.kleston.projects.delivery.model.jooq.tables.Restaurants;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Delivery extends SchemaImpl {

    private static final long serialVersionUID = 584573052;

    /**
     * The reference instance of <code>delivery</code>
     */
    public static final Delivery DELIVERY = new Delivery();

    /**
     * The table <code>delivery.accounts</code>.
     */
    public final Accounts ACCOUNTS = br.com.kleston.projects.delivery.model.jooq.tables.Accounts.ACCOUNTS;

    /**
     * The table <code>delivery.orders</code>.
     */
    public final Orders ORDERS = br.com.kleston.projects.delivery.model.jooq.tables.Orders.ORDERS;

    /**
     * The table <code>delivery.orders_foods</code>.
     */
    public final OrdersFoods ORDERS_FOODS = br.com.kleston.projects.delivery.model.jooq.tables.OrdersFoods.ORDERS_FOODS;

    /**
     * The table <code>delivery.products</code>.
     */
    public final Products PRODUCTS = br.com.kleston.projects.delivery.model.jooq.tables.Products.PRODUCTS;

    /**
     * The table <code>delivery.restaurants</code>.
     */
    public final Restaurants RESTAURANTS = br.com.kleston.projects.delivery.model.jooq.tables.Restaurants.RESTAURANTS;

    /**
     * No further instances allowed
     */
    private Delivery() {
        super("delivery", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Accounts.ACCOUNTS,
            Orders.ORDERS,
            OrdersFoods.ORDERS_FOODS,
            Products.PRODUCTS,
            Restaurants.RESTAURANTS);
    }
}
