/*
 * This file is generated by jOOQ.
 */
package br.com.kleston.projects.delivery.model.jooq;


import br.com.kleston.projects.delivery.model.jooq.tables.Account;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in delivery
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>delivery.account</code>.
     */
    public static final Account ACCOUNT = br.com.kleston.projects.delivery.model.jooq.tables.Account.ACCOUNT;
}
