version: '3'

services:
  delivery_mysql:
    container_name: delivery_mysql
    image: mysql
    restart: always
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=extreme123
      - MYSQL_DATABASE=delivery
      - MYSQL_USER=delivery
      - MYSQL_PASSWORD=delivery
    volumes:
      - "./mysql_scripts:/docker-entrypoint-initdb.d"

  delivery_rabbitmq:
    container_name: delivery_rabbitmq
    image: rabbitmq:management
    restart: always
    ports:
      - "4369:4369"
      - "5671:5671"
      - "5672:5672"
      - "15671:15671"
      - "15672:15672"