/*
 * This file is generated by jOOQ.
 */
package br.com.kleston.projects.delivery.model.jooq.tables.records;


import br.com.kleston.projects.delivery.model.jooq.tables.OrdersProducts;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrdersProductsRecord extends UpdatableRecordImpl<OrdersProductsRecord> implements Record3<Long, Long, Long> {

    private static final long serialVersionUID = -1700827175;

    /**
     * Setter for <code>delivery.orders_products.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>delivery.orders_products.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>delivery.orders_products.id_order</code>.
     */
    public void setIdOrder(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>delivery.orders_products.id_order</code>.
     */
    public Long getIdOrder() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>delivery.orders_products.id_product</code>.
     */
    public void setIdProduct(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>delivery.orders_products.id_product</code>.
     */
    public Long getIdProduct() {
        return (Long) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Long, Long, Long> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Long, Long, Long> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return OrdersProducts.ORDERS_PRODUCTS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return OrdersProducts.ORDERS_PRODUCTS.ID_ORDER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return OrdersProducts.ORDERS_PRODUCTS.ID_PRODUCT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getIdOrder();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component3() {
        return getIdProduct();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getIdOrder();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getIdProduct();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrdersProductsRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrdersProductsRecord value2(Long value) {
        setIdOrder(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrdersProductsRecord value3(Long value) {
        setIdProduct(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrdersProductsRecord values(Long value1, Long value2, Long value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OrdersProductsRecord
     */
    public OrdersProductsRecord() {
        super(OrdersProducts.ORDERS_PRODUCTS);
    }

    /**
     * Create a detached, initialised OrdersProductsRecord
     */
    public OrdersProductsRecord(Long id, Long idOrder, Long idProduct) {
        super(OrdersProducts.ORDERS_PRODUCTS);

        set(0, id);
        set(1, idOrder);
        set(2, idProduct);
    }
}
